apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: {{ .Values.jenkins.name }}
  namespace: {{ .Values.jenkins.namespace }}
spec:
  configurationAsCode:
    configurations:
      - name: jenkins-{{ .Values.jenkins.name }}-casc
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.277.4-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi

    plugins:
{{- range $plugin := .Values.jenkins.controller.plugins }}
      - name: {{ $plugin.name }}
        version: "{{ $plugin.version }}"
{{- end }}

    {{- if .Values.jenkins.controller.nodeSelector }}
    nodeSelector:
{{ toYaml .Values.jenkins.controller.nodeSelector | indent 6 }}
    {{- end }}

{{- if .Values.jenkins.controller.serviceAnnotations }}
  service:
    annotations:
{{ toYaml .Values.jenkins.controller.serviceAnnotations | indent 6 }}
{{- end }}

  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git