services:
  controller:
    image: controller:local

    ports:
      - 8080:8080
      - 50000:50000

    volumes:
      # Ensure the controller's home directory maps to a Docker volume
      # This allows upgrading the jenkins container but keeping all history
      - type: volume
        source: controller-home
        target: /var/jenkins_home

      # Make GCP Service Account credential file available to controller
      - type: bind
        source: ./google_application_credentials.json
        target: /google_application_credentials.json
        bind:
          propagation: rprivate
          create_host_path: false
        read_only: true

    healthcheck:
      test: curl --fail http://localhost:8080/login || exit 1
      interval: 5s
      retries: 20
      start_period: 10s
      timeout: 5s

    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
      WEB_UI_URL: http://localhost:8080
      SEED_JOB_REPO_URL: https://github.com/falldamagestudio/UE-Jenkins-Jobs
      SEED_JOB_BRANCH: 2.x
      GOOGLE_APPLICATION_CREDENTIALS: /google_application_credentials.json

    networks:
      - controller-vm

volumes:
  controller-home:
    name: controller-home

networks:
  controller-vm:
    driver: bridge
    name: controller-vm
