
# A Jenkins server that has lots of jobs in the queue can take a lot of time to start up.
# The default startup probe settings make Kubernetes terminate the pod for taking too
#  long to boot after ~2m30s and restart it. This results in a heavily loaded Jenkins
#  getting stuck in an initialiation loop if it is restarted. Better give the controller
#  almost an hour to fully start up.
controller:
  probes:
    startupProbe:
      failureThreshold: 360

