controller:
  backendconfig:
    enabled: true

    apiVersion: cloud.google.com/v1

    name: jenkins-controller

    # Activate Identity-Aware Proxy for Ingress
    # Reference: https://cloud.google.com/iap/docs/enabling-kubernetes-howto#kubernetes-configure
    spec:
      iap:
        enabled: true
        oauthclientCredentials:
          secretName: iap-configuration
