controller:
  secondaryingress_backendconfig:
    enabled: true

    apiVersion: cloud.google.com/v1

    name: jenkins-controller-secondary-ingress

    spec:
      # Increase HTTP timeout to allow long-running WebSocket connections
      # Reference: https://cloud.google.com/load-balancing/docs/backend-service#timeout-setting
      # Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#timeout
      timeoutSec: 1000000
