controller:
  secondaryingress:
    enabled: true

    # Allow only the URLs necessary for the inbound agent in WebSocket mode
    paths: [

        # TODO: Does this URL really need to be exposed?
        "/", 

        # Swarm agents will connect to these URLs to fetch the Jenkins version
        "/api",
        "/api/",
        "/crumbIssuer/api/xml",
        "/plugin/swarm/createSlave",
        "/computer/*",

        # WebSocket agents will connect to this URL when establishing the WebSocket connection
        "/wsagents/",

        # If a a websocket agent loses connection and wants to reconnect, it will repeatedly poll this URL until there is a 200 response;
        #   then it attempts to re-establish a WebSocket connection again
        "/login"
      ]

    annotations:
      # Use an internal HTTP(S) load balancer
      # Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress
      kubernetes.io/ingress.class: "gce-internal"

      # Connect load balancer to a static IP address
      # The value of the 'undefined' parameter should be provided as an extra commandline argument when calling 'helm install'
      # Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress#static_ip_addressing
      kubernetes.io/ingress.regional-static-ip-name: "undefined"
