services:
  controller:
    image: controller:local

    volumes:
      # Map shared CasC config files into container
      - type: bind
        source: ../../casc_configs/shared
        target: /var/jenkins_home/casc_configs/shared
        bind:
          propagation: rprivate
          create_host_path: false
        read_only: true

      # Map local CasC config files into container
      - type: bind
        source: ../../casc_configs/local
        target: /var/jenkins_home/casc_configs/local
        bind:
          propagation: rprivate
          create_host_path: false
        read_only: true

      # Map shared init.groovy.d files into container
      - type: bind
        source: ../../init.groovy.d/shared
        target: /var/jenkins_home/init.groovy.d
        bind:
          propagation: rprivate
          create_host_path: false
        read_only: true

      # TODO: make Plastic config files available to controller

    environment:
      WEB_UI_URL: http://localhost:8080
