# - name: Ensure Docker Compose folder exists
#   ansible.builtin.file:
#     path: /var/controller_stuff
#     state: directory
#     mode: '0644'

- name: copy Docker Compose files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ group }}"
    owner: "{{ user }}"
  with_items: "{{ docker_compose_files }}"

- name: Create casc_configs folder
  file:
    path: "{{ home }}/casc_configs"
    state: directory
    mode: '0644'
    group: "{{ group }}"
    owner: "{{ user }}"

- name: copy CasC configs
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    delete: true
  with_items: "{{ casc_config_folders }}"

- name: Create .plastic4 folder
  file:
    path: "{{ home }}/.plastic4"
    state: directory
    mode: '0644'
    group: "{{ group }}"
    owner: "{{ user }}"

- name: Create empty google_application_credentials.json
  file:
    path: "{{ home }}/google_application_credentials.json"
    state: touch
    mode: '0644'
    group: "{{ group }}"
    owner: "{{ user }}"
