{{- if .Values.controller.secondaryservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{template "jenkins.fullname" . }}-secondary
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}-secondary'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
    {{- if .Values.controller.serviceLabels }}
{{ toYaml .Values.controller.serviceLabels | indent 4 }}
    {{- end }}
{{- if .Values.controller.secondaryservice.annotations }}
  annotations:
{{ toYaml .Values.controller.secondaryservice.annotations | indent 4 }}
{{- end }}
spec:
  {{- if (and (eq .Values.controller.secondaryservice.serviceType "ClusterIP") (not (empty .Values.controller.secondaryservice.clusterIP))) }}
  clusterIP: {{.Values.controller.secondaryservice.clusterIP}}
  {{- end }}
  ports:
    - port: {{.Values.controller.secondaryservice.servicePort}}
      name: http
      targetPort: {{ .Values.controller.targetPort }}
      {{- if (and (eq .Values.controller.secondaryservice.serviceType "NodePort") (not (empty .Values.controller.secondaryservice.nodePort))) }}
      nodePort: {{.Values.controller.secondaryservice.nodePort}}
      {{- end }}
{{- range $index, $port := .Values.controller.secondaryservice.extraPorts }}
    - port: {{ $port.port }}
      name: {{ $port.name }}
      targetPort: {{ $port.port }}
{{- end }}
  selector:
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  type: {{.Values.controller.secondaryservice.serviceType}}
  {{if eq .Values.controller.secondaryservice.serviceType "LoadBalancer"}}
{{- if .Values.controller.secondaryservice.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.controller.secondaryservice.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  {{if .Values.controller.secondaryservice.loadBalancerIP}}
  loadBalancerIP: {{.Values.controller.secondaryservice.loadBalancerIP}}
  {{end}}
  {{end}}
{{- end }}