{{- if .Values.controller.managedsslcertificate.enabled }}

apiVersion: {{ .Values.controller.managedsslcertificate.apiVersion }}
kind: ManagedCertificate
metadata:
  name: {{ .Values.controller.managedsslcertificate.name }}
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
{{- if .Values.controller.managedsslcertificate.labels }}
{{ toYaml .Values.controller.managedsslcertificate.labels | indent 4 }}
{{- end }}
{{- if .Values.controller.managedsslcertificate.annotations }}
  annotations:
{{ toYaml .Values.controller.managedsslcertificate.annotations | indent 4 }}
{{- end }}
spec:
  domains:
    {{ .Values.controller.managedsslcertificate.domains }}

{{- end }}
