- name: Restart 'controller-agent' service, and collect error messages on failure
  block:
    - name: Capture start timestamp, in case we need to retrieve logs
      ansible.builtin.shell: date --utc "+%Y-%m-%d %H:%M:%S UTC"
      register: role_start_timestamp
      changed_when: false

    - name: Restart 'controller-agent' service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted

    # Print logs after successful service operation

    - name: Fetch output from invoking docker, and the container
      ansible.builtin.shell: journalctl --since "{{ role_start_timestamp.stdout }}" "CONTAINER_NAME={{ docker_container_name }}" + "_SYSTEMD_UNIT={{ service_name }}.service"
      register: docker_output

    - name: Print output to console
      ansible.builtin.debug:
        msg: "{{ docker_output.stdout }}"

  rescue:

    # Print logs after failed service operation

    - name: Fetch output from invoking docker, and the container
      ansible.builtin.shell: journalctl --since "{{ role_start_timestamp.stdout }}" "CONTAINER_NAME={{ docker_container_name }}" + "_SYSTEMD_UNIT={{ service_name }}.service"
      register: docker_output

    - name: Print output to console
      ansible.builtin.fail:
        msg: "{{ docker_output.stdout }}"
