- name: Create 'controller' user
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
#      shell: /sbin/nologin
    state: present
    create_home: yes

- name: Create 'controller' systemd service file
  ansible.builtin.template:
    src: templates/{{ service_name }}.service.j2
    dest: /lib/systemd/system/{{ service_name }}.service    

- name: Re-read systemd configurations
  ansible.builtin.systemd:
    daemon_reload: true
