services:
  controller-agent:
    image: europe-west1-docker.pkg.dev/fd-ue-jenkins-buildsystem/docker-build-artifacts/linux-swarm-agent:commit-b65a821

    volumes:

      # Make Plastic credential files available to controller agent
      - type: bind
        source: ./.plastic4
        target: /home/jenkins/.plastic4
        bind:
          propagation: rprivate
          create_host_path: false
        read_only: false
