---
- hosts: remote
  become: yes
  gather_facts: true
  pre_tasks:
  roles:
    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent
  tasks:
  vars_files:
    - "{{ env_path }}/env_vars.yml"
    - "{{ global_env_path }}/env_vars.yml"
