# Disable Script Security globally for Job DSL
# In some sense this presents a potential security risk (any Job DSL code is trusted by default);
#  the other options are to either run any Job DSL code in the Groovy Sandbox + whitelist any necessary functions,
#  or to manually perform whitelisting of individual .groovy files from the seed job before running those scripts
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
