jenkins:

  # should be in auth.yaml
  # Disable access for anonymous users
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  # should be in auth.yaml
  # Configure google credentials provider plugin's OAuth settings
  securityRealm:
    googleOAuth2:
      clientId: ${OAUTH2_CLIENT_ID}
      clientSecret: ${OAUTH2_CLIENT_SECRET}

  disableRememberMe: false
  mode: NORMAL
  numExecutors: 1
  projectNamingStrategy: "standard"
  markupFormatter:
    plainText
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
