jenkins:
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 0
  projectNamingStrategy: "standard"
  markupFormatter:
    plainText
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
