jenkins:
  disableRememberMe: false
  markupFormatter:
    plainText
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
