jobs:
  - script: >
      job('Seed Job') {

        // Repository which contains job DSL scripts
        scm {
          git {
            remote {
              url('https://github.com/falldamagestudio/Alara-Jenkins-Jobs')
              credentials('github-user')
            }
            branch('*/main')
          }
        }

        steps {
          jobDsl {

            // Scan recursively through jobs repository for Job DSL scripts
            targets "**/*.groovy"

            // Fail build if generated item(s) have the same name as existing items already managed by another seed job.
            // Reference: https://www.jenkins.io/doc/pipeline/steps/job-dsl/
            failOnSeedCollision true

            // When a previously generated job/view/config file no longer is being referenced, delete the item
            // Reference: https://www.jenkins.io/doc/pipeline/steps/job-dsl/
            removedJobAction "DELETE"
            removedViewAction "DELETE"
            removedConfigFilesAction "DELETE"
          }
        }
      }